language: php

php:
  - 7.0
  - 7.1
  - nightly

install:
  - composer install
  - mysqld --version

before_script:
  - echo '<?php $autoloader = require(__DIR__."/../vendor/autoload.php"); const DB_HOST = "localhost"; const DB_USER = "root"; const DB_PASS = "";' > test/phpunit_bootstrap.php
  - mysql -u root -e "CREATE DATABASE connectiontest; CREATE TABLE connectiontest.main SELECT 1 AS a, 2 AS b; INSERT INTO connectiontest.main VALUES (5, 6);"
 
script: phpdbg -qrr vendor/bin/phpunit --coverage-text

cache:
  directories:
    - $HOME/.composer/cache
